KhoborSite/Controllers/ContactController.cs
using Business.DI;
using Business.Services.FormComponents;
using Business.ViewModels;
using CMS.CustomTables;
using CMS.DataEngine;
using CMS.SiteProvider;
using System;
using System.Linq;
using System.Web.Mvc;

namespace KhoborSite.Controllers
{
    public class ContactController : BaseController
    {
        protected const string FormName = "ContactRegistration";
        protected const string TableName = "customtable.contact";
        protected IBizFormService BizFormService { get; }

        public ContactController(
            IBusinessDependencies dependencies,
            IBizFormService bizFormService) : base(dependencies)
        {
            BizFormService = bizFormService ?? throw new ArgumentNullException(nameof(bizFormService));
        }

        // GET: Contact
        public ActionResult Index()
        {
            return View(BizFormService.GetBizFormVM(FormName, SiteContext.CurrentSiteID));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(FormComponentViewModel vm)
        {
            var model = BizFormService.GetBizFormVM(FormName, SiteContext.CurrentSiteID, vm.ElementId, ControllerContext);

            // Save the form data
            if (model != null && ModelState.IsValid)
            {
                var name = model.FormComponents.FirstOrDefault(c => c.Name == "Name")?.GetObjectValue() + string.Empty;
                var address = model.FormComponents.FirstOrDefault(c => c.Name == "Address")?.GetObjectValue() + string.Empty;

                var items = address.Split(';');
                var postalCode = items.Length > 0 ? items[0] : string.Empty;
                var geoName = items.Length > 1 ? items[1] : string.Empty;
                var countryCode = items.Length > 2 ? items[2] : string.Empty;

                // Gets the custom table
                DataClassInfo customTable = DataClassInfoProvider.GetDataClassInfo(TableName);
                if (customTable != null)
                {
                    // Creates a new custom table item
                    CustomTableItem newCustomTableItem = CustomTableItem.New(TableName);

                    // Sets the values for the fields of the custom table (ItemText in this case)
                    newCustomTableItem.SetValue("Name", name);
                    newCustomTableItem.SetValue("PostalCode", postalCode);
                    newCustomTableItem.SetValue("GeoName", geoName);
                    newCustomTableItem.SetValue("CountryCode", countryCode);

                    // Save the new custom table record into the database
                    newCustomTableItem.Insert();

                    model.FormComponents.ForEach(c => c.SetObjectValue(null));
                }
            }

            return View(BizFormService.GetBizFormVM(FormName, SiteContext.CurrentSiteID));
        }
    }
}

KhoborSite/Views/Shared/_Layout.cshtml
@using Kentico.PageBuilder.Web.Mvc

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700italic&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">

    @Styles.Render("~/Content/css")

    @RenderSection("styles", required: false)

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    @Scripts.Render("~/bundles/scripts")

    @RenderSection("scripts", required: false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Khobor", "Index", "Contact", new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Contact", "Index", "Contact")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
</body>
</html>